### ISSUE TITLE
Cross compiling ardupilot with clang?

### ISSUE THREAD

**Issue by Lqs66** [WUSTL-CSPL/ARI#2]
To instrument ArduPilot using LLVM, Clang should be substituted for GCC as the compiler prior to compilation. For guidance on altering the compiler and platform target, please consult the files ARI/ardupilot/source_me_sitl_bc_step_zero.txt and ARI/ardupilot/wscript.

_Originally posted by @J1nwenWang in https://github.com/WUSTL-CSPL/ARI/issues/1#issuecomment-1801121884_

I looked at the file you told me about, and I'm wondering if this applies to "--target=arm-none-eabi"?

**Comment by J1nwenWang** [comment]
I have never tried that. Please have a try.
